# Numpy Practice session

In [1]:
# pip Install numpy
# import numpy as np, is the command used in python to importy numpy library

# Create an array

In [2]:
#pip install numpy

In [3]:
import numpy as np
np.array(["Pakora",'Samosa', "Raita","jalebi"])


array(['Pakora', 'Samosa', 'Raita', 'jalebi'], dtype='<U6')

In [4]:
#numpy 1-D array
import numpy as np
food = np.array(["Pakora",'Samosa', "Raita","jalebi"])
food

array(['Pakora', 'Samosa', 'Raita', 'jalebi'], dtype='<U6')

In [5]:
price = np.array([5,5,5,10,15])
price

array([ 5,  5,  5, 10, 15])

In [6]:
type(price)
type(food)

numpy.ndarray

In [7]:
len(food)

4

In [8]:
food[2]

'Raita'

In [9]:
food[0:]

array(['Pakora', 'Samosa', 'Raita', 'jalebi'], dtype='<U6')

In [10]:
price.mean()

8.0

In [11]:
price

array([ 5,  5,  5, 10, 15])

In [12]:
# zeros
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
#ones
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
#empty
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
#range
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
# specfic interval
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
#line space
np.linspace (1,10,num=50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
#specify data type
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [19]:
np.ones(5,dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array Functions

In [20]:
a = np.array([10,12,40,50,10.5,5.5])
a

array([10. , 12. , 40. , 50. , 10.5,  5.5])

In [21]:
np.sort(a)

array([ 5.5, 10. , 10.5, 12. , 40. , 50. ])

In [22]:
b = np.array([55,57,88,90])
b

array([55, 57, 88, 90])

In [23]:
np.concatenate((a,b))

array([10. , 12. , 40. , 50. , 10.5,  5.5, 55. , 57. , 88. , 90. ])

In [24]:
c = np.concatenate((a,b))
np.sort(c)

array([ 5.5, 10. , 10.5, 12. , 40. , 50. , 55. , 57. , 88. , 90. ])

# Two dimensional arrays

In [25]:
# a = np.array([[2,4],[5,6]])
# a

In [26]:
# b =np.array([4,5])
# b

In [27]:
# c =np.concatenate((a,b),axis=0))
# c

In [28]:
# x = np.array([[1, 2], [3, 4]])
# y = np.array([[5, 6]])

In [29]:
# np.concatenate((x, y), axis=0)

In [30]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [31]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])